export const AVAILABLE_COURSES = [
  { code: "IF-0001", name: "DESARROLLO DE SOFTWARE" },
  { code: "IF-0002", name: "INTRODUCCIÓN A LA INFORMÁTICA EMPRESARIAL" },
  { code: "IF-0003", name: "MATEMÁTICA BÁSICA PARA INFORMÁTICA EMPRESARIAL" },
  { code: "IF-0004", name: "DESARROLLO DE SOFTWARE II" },
  { code: "IF-0005", name: "MATEMÁTICAS DISCRETAS PARA INFORMÁTICA EMPRESARIAL" },
  { code: "IF-0006", name: "DESARROLLO DE SOFTWARE III" },
  { code: "IF-0007", name: "BASES DE DATOS I" },
  { code: "IF-0008", name: "CÁLCULO I PARA INFORMÁTICA EMPRESARIAL" },
  { code: "IF-3001", name: "ALGORITMOS Y ESTRUCTURAS DE DATOS" },
  { code: "IF-0009", name: "DESARROLLO DE SOFTWARE IV" },
  { code: "IF-0010", name: "BASES DE DATOS II" },
  { code: "IF-0011", name: "REDES DE COMPUTADORAS" },
  { code: "IF-0012", name: "ÁLGEBRA LINEAL PARA INFORMÁTICA EMPRESARIAL" },
  { code: "IF-0015", name: "INTRODUCCIÓN A LA ADMINISTRACIÓN DE NEGOCIOS" },
  { code: "IF-0016", name: "INTRODUCCIÓN A LA ESTADÍSTICA Y ANÁLISIS DE DATOS" },
  { code: "IF-0017", name: "MÉTODOS NUMÉRICOS Y ANÁLISIS COMPUTACIONAL" },
  { code: "IF-0019", name: "SEGURIDAD EN SISTEMAS INFORMÁTICOS" },
  { code: "IF-7201", name: "GESTIÓN DE PROYECTOS" },
];

export const COURSE_COLORS = {
  'IF-0001': { icon: 'ti-code', color: '#5B4FD4', bgColor: '#f0eeff', borderColor: '#c4bef5' },
  'IF-0002': { icon: 'ti-book', color: '#378ADD', bgColor: '#E6F1FB', borderColor: '#B5D4F4' },
  'IF-0003': { icon: 'ti-math-function', color: '#D97B1A', bgColor: '#fff8ec', borderColor: '#f5d8a0' },
  'IF-0004': { icon: 'ti-code', color: '#D4537E', bgColor: '#fff0f5', borderColor: '#f4bad0' },
  'IF-0005': { icon: 'ti-math-function', color: '#1D9E75', bgColor: '#edfaf4', borderColor: '#9fe1cb' },
  'IF-0006': { icon: 'ti-code', color: '#5B4FD4', bgColor: '#f0eeff', borderColor: '#c4bef5' },
  'IF-0007': { icon: 'ti-database', color: '#378ADD', bgColor: '#E6F1FB', borderColor: '#B5D4F4' },
  'IF-0008': { icon: 'ti-math-function', color: '#D97B1A', bgColor: '#fff8ec', borderColor: '#f5d8a0' },
  'IF-3001': { icon: 'ti-binary-tree', color: '#D4537E', bgColor: '#fff0f5', borderColor: '#f4bad0' },
  'IF-0009': { icon: 'ti-code', color: '#1D9E75', bgColor: '#edfaf4', borderColor: '#9fe1cb' },
  'IF-0010': { icon: 'ti-database', color: '#5B4FD4', bgColor: '#f0eeff', borderColor: '#c4bef5' },
  'IF-0011': { icon: 'ti-network', color: '#D97B1A', bgColor: '#fff8ec', borderColor: '#f5d8a0' },
  'IF-0012': { icon: 'ti-math-function', color: '#378ADD', bgColor: '#E6F1FB', borderColor: '#B5D4F4' },
  'IF-0015': { icon: 'ti-briefcase', color: '#D4537E', bgColor: '#fff0f5', borderColor: '#f4bad0' },
  'IF-0016': { icon: 'ti-chart-bar', color: '#1D9E75', bgColor: '#edfaf4', borderColor: '#9fe1cb' },
  'IF-0017': { icon: 'ti-math-function', color: '#5B4FD4', bgColor: '#f0eeff', borderColor: '#c4bef5' },
  'IF-0019': { icon: 'ti-lock', color: '#D97B1A', bgColor: '#fff8ec', borderColor: '#f5d8a0' },
  'IF-7201': { icon: 'ti-layout-list', color: '#378ADD', bgColor: '#E6F1FB', borderColor: '#B5D4F4' },
};
